// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CalculatorController from "./calculator_controller"
application.register("calculator", CalculatorController)

import ChartController from "./chart_controller"
application.register("chart", ChartController)

import EditableTableController from "./editable_table_controller"
application.register("editable-table", EditableTableController)

import FilterController from "./filter_controller"
application.register("filter", FilterController)

import SelectableController from "./selectable_controller"
application.register("selectable", SelectableController)

import ShoppingController from "./shopping_controller"
application.register("shopping", ShoppingController)

import TableController from "./table_controller"
application.register("table", TableController)

import TypingController from "./typing_controller"
application.register("typing", TypingController)
